### Numpy random distribution assignment

In [1]:
import numpy as np
from numpy import random as rd

In [2]:
# 1
coin=np.array([4, 7, 8, 8, 6, 7, 6, 5, 4, 3])

In [3]:
# using the normal distribution
#(loc(mean),scale(st.deviation),size)
loc=np.mean(coin)
scale=np.std(coin)

In [4]:
loc

5.8

In [5]:
scale=round(scale,2)
scale

1.66

In [6]:
nxt100=rd.normal(loc,scale,100)

In [7]:
nxt100=np.trunc(nxt100)

In [8]:
nxt100

array([8., 9., 6., 7., 6., 5., 7., 7., 6., 7., 7., 4., 4., 7., 9., 8., 4.,
       6., 4., 8., 4., 4., 6., 5., 5., 6., 5., 4., 5., 6., 5., 8., 6., 4.,
       4., 4., 6., 4., 3., 2., 4., 8., 3., 7., 6., 3., 6., 4., 4., 5., 7.,
       5., 3., 3., 6., 5., 6., 5., 5., 5., 5., 5., 5., 7., 3., 8., 5., 9.,
       4., 8., 6., 4., 6., 4., 3., 3., 7., 5., 6., 4., 3., 6., 5., 6., 5.,
       3., 7., 6., 7., 3., 5., 5., 5., 3., 5., 4., 4., 6., 5., 6.])

In [9]:
# 2
score=rd.normal(70,10,50)

In [10]:
score

array([83.06039834, 82.39304634, 77.0790518 , 62.28073436, 78.6518913 ,
       75.86919741, 76.3117891 , 73.14029823, 69.71767158, 64.79319252,
       60.12170401, 57.27444698, 64.06603041, 81.77303876, 74.81843709,
       60.95671254, 58.15423317, 66.13482203, 83.11555837, 72.66083708,
       61.75531083, 78.23205032, 58.32423903, 73.48273234, 76.81744108,
       56.36594057, 86.33026842, 65.84443349, 61.85723673, 72.19523395,
       72.7819243 , 64.68249641, 78.38792135, 76.10106085, 74.47746907,
       50.68131898, 74.68296178, 70.76974911, 52.9629642 , 68.36304114,
       82.58606627, 73.30081518, 55.56913397, 69.57694053, 65.87605789,
       69.52372803, 70.15785223, 65.48647411, 65.87011156, 71.78706293])

In [11]:
score=np.around(score,2)
score

array([83.06, 82.39, 77.08, 62.28, 78.65, 75.87, 76.31, 73.14, 69.72,
       64.79, 60.12, 57.27, 64.07, 81.77, 74.82, 60.96, 58.15, 66.13,
       83.12, 72.66, 61.76, 78.23, 58.32, 73.48, 76.82, 56.37, 86.33,
       65.84, 61.86, 72.2 , 72.78, 64.68, 78.39, 76.1 , 74.48, 50.68,
       74.68, 70.77, 52.96, 68.36, 82.59, 73.3 , 55.57, 69.58, 65.88,
       69.52, 70.16, 65.49, 65.87, 71.79])

In [12]:
#3
cust=rd.poisson(3,1000)
cust

array([3, 2, 2, 3, 2, 5, 1, 2, 0, 1, 3, 2, 4, 1, 3, 0, 2, 6, 5, 2, 1, 3,
       0, 3, 5, 4, 5, 4, 4, 4, 2, 3, 4, 2, 4, 4, 1, 3, 1, 4, 6, 4, 3, 2,
       6, 6, 3, 2, 2, 5, 1, 2, 5, 0, 3, 5, 1, 5, 2, 2, 5, 5, 1, 3, 3, 2,
       1, 2, 1, 4, 4, 2, 2, 2, 3, 3, 4, 5, 5, 4, 1, 3, 5, 3, 4, 2, 5, 2,
       1, 3, 3, 3, 2, 3, 3, 1, 7, 2, 5, 0, 3, 2, 3, 2, 5, 2, 4, 5, 1, 1,
       4, 3, 3, 4, 2, 3, 3, 3, 4, 4, 6, 2, 1, 4, 5, 1, 3, 4, 1, 3, 2, 5,
       2, 4, 4, 2, 4, 5, 1, 2, 7, 2, 3, 1, 2, 1, 4, 1, 1, 3, 3, 3, 1, 0,
       4, 3, 1, 2, 1, 2, 2, 1, 1, 0, 2, 4, 2, 6, 2, 2, 1, 2, 4, 1, 1, 2,
       5, 2, 2, 5, 3, 2, 5, 2, 1, 5, 1, 4, 3, 2, 1, 2, 3, 4, 5, 2, 3, 4,
       2, 2, 5, 1, 2, 5, 5, 2, 1, 5, 5, 8, 4, 2, 3, 5, 2, 7, 2, 2, 6, 5,
       2, 1, 3, 3, 3, 6, 4, 2, 3, 0, 3, 3, 5, 5, 1, 5, 4, 4, 1, 5, 6, 1,
       2, 3, 5, 6, 4, 2, 5, 2, 3, 2, 0, 4, 2, 1, 1, 2, 1, 4, 0, 1, 2, 0,
       4, 4, 0, 3, 6, 2, 3, 0, 5, 1, 2, 3, 4, 1, 4, 3, 4, 5, 1, 2, 6, 5,
       2, 3, 2, 2, 2, 5, 2, 4, 1, 3, 1, 4, 2, 3, 4,

In [13]:
print(np.sum(cust>=7)/len(cust))

0.031


In [14]:
# 4
defects=rd.binomial(50,0.05,1)
defects

array([2])